In [13]:
import pptk
import numpy as np
import glob
import os

In [ ]:
!pip uninstall pptk

Found existing installation: pptk 0.1.0
Uninstalling pptk-0.1.0:
  Would remove:
    /home/bryan/anaconda3/envs/pptk/lib/python3.7/site-packages/pptk-0.1.0.dist-info/*
    /home/bryan/anaconda3/envs/pptk/lib/python3.7/site-packages/pptk/*
Proceed (Y/n)? 

In [7]:
# Set your folder path
folder_path = "/home/bryan/pointcloud_data/hsinchu_q2" # Change this to your actual folder path

# Get all .npy files and sort them for consistent ordering
npy_files = sorted(glob.glob(os.path.join(folder_path, "*.npy")))
print(f"Found {len(npy_files)} .npy files:")

Found 8134 .npy files:


In [14]:
pose = np.load("/home/bryan/pointcloud_data/airport_q2_poses.npy")

In [17]:
pose

array([(    0, [[-0.63437259, -0.77086519, -0.05777782], [ 0.77234913, -0.6351735 , -0.00560734], [-0.03237644, -0.04818179,  0.99831372]], [1357.497049  , 1166.80624905,   43.86530904]),
       (    6, [[-0.63454225, -0.77076502, -0.05724867], [ 0.77224678, -0.63529102, -0.00634278], [-0.03148077, -0.04823487,  0.9983398 ]], [1357.48124261, 1166.76413416,   43.85610926]),
       (  257, [[-0.63747002, -0.76831651, -0.0576343 ], [ 0.76973911, -0.63834567, -0.00406171], [-0.03366993, -0.04695259,  0.9983295 ]], [1357.41067858, 1166.70935634,   43.87263415]),
       ...,
       (10707, [[-0.74046583,  0.67205242,  0.00747672], [-0.67209268, -0.74039648, -0.01022164], [-0.00133374, -0.01259382,  0.99991981]], [1235.14457718, 1349.2715822 ,   40.66364486]),
       (10708, [[-0.74567874,  0.66628491,  0.00525668], [-0.66629445, -0.74559725, -0.01168118], [-0.00386363, -0.0122129 ,  0.99991796]], [1235.95522476, 1348.36298029,   40.68353726]),
       (10709, [[-0.74838681,  0.66324636,  0.00

In [8]:
test = np.load('/home/bryan/pointcloud_data/hsinchu_q2/10532.npy')

In [11]:
test.shape

(139008,)

In [35]:
n = 0
m = 200
selected_files = npy_files[n:m]
arrays = [np.load(file) for file in selected_files]
selected_data = np.concatenate(arrays, axis=0)
data = selected_data
coordinates = np.array([item[0] for item in data])
intensity = np.array([item[1] for item in data])
color = np.array([item[2][1] for item in data])
line_type = np.array([item[2][2] for item in data])

In [36]:
np.unique(line_type,return_counts=True)

(array([-1,  2,  3,  4], dtype=int32),
 array([27315505,    95418,   144580,    99793]))

In [37]:
np.unique(color,return_counts=True)


(array([-1,  4,  5,  6], dtype=int32),
 array([27315505,    58963,   211569,    69259]))

In [12]:
viewer = pptk.viewer(test['xyz'])

In [ ]:
viewer = pptk.viewer(coordinates)
viewer.attributes(intensity,color,color_array[line_type])
viewer.set(point_size = 0.001)

In [31]:
viewer.attributes(intensity,color,color_array[line_type])

In [32]:
viewer.color_map('jet', scale=[0, 50])

In [33]:
viewer.color_map('jet', scale=[-1, 6])

In [27]:
color_array[line_type]

array([[0.5, 0.5, 1. ],
       [0.5, 0.5, 1. ],
       [0.5, 0.5, 1. ],
       ...,
       [0.5, 0.5, 1. ],
       [0.5, 0.5, 1. ],
       [0.5, 0.5, 1. ]])

In [ ]:
color_mapping = {
    1: [0, 0, 1],        # none -> blue
    2: [1, 1, 1],        # solid -> white
    3: [0.5, 0.5, 0.5],  # broken -> grey
    4: [1, 1, 0],        # solid solid -> yellow
    5: [1, 0.5, 0],      # solid broken -> orange
    6: [1, 0.5, 0],      # broken solid -> orange
    7: [0.5, 0.5, 1],    # broken broken -> light blue
    8: [0.5, 0.5, 1],    # botts dots -> light blue
    9: [0.5, 0.5, 1],    # grass -> light blue
    10: [0.5, 0.5, 1],   # curb -> light blue
    11: [0.5, 0.5, 1],   # custom -> light blue
    12: [0.5, 0.5, 1]    # edge -> light blue
}
max_key = max(color_mapping.keys())
color_array = np.zeros((max_key + 1, 3))
for k, v in color_mapping.items():
    color_array[k] = v
